services:
  - docker
before_install:
  - docker build -t testimage .
 # - docker run testimage /bin/sh -c "cd /root/testimage; bundle exec foreman start;"
 #- docker ps -a
 # - docker run testimage /bin/sh -c "cd /root/testimage; bundle exec rake test"
script:
  - bundle exec rake test
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master  
