language: minimal
services:
  - docker
before_install:
  - docker build -t testimage .
  - docker run -it --name testimage testimage
  - docker commit testimage hyperionext/testrepo1

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master  
